# This config applies recursively to all sub-directories.

# Multiple directories can use separate SOPS configs.

# Contributors using the sops CLI to create and encrypt files won’t have to worry
# about specifying the proper key for the target cluster or namespace.
# Therefore, they can just encrypt files with `sops -e file.yaml`

# Private key should be in ./cluster/{name}/sops.agekey

# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # Dev secrets
  - path_regex: .*dev/.*values-secret.yaml
    age: age1ln0hyfv26nu7c9ljq99aulgqxu3y2l3jggv9ggt9pekqvz8tu34q9a4zwt
  - path_regex: .*dev/.*.yaml
    encrypted_regex: ^(data|stringData)$
    age: age1ln0hyfv26nu7c9ljq99aulgqxu3y2l3jggv9ggt9pekqvz8tu34q9a4zwt
  # Staging secrets
  - path_regex: .*staging/.*values-secret.yaml
    age: age1fapwknfa6lm0rmpxe4dkuyjpcz9wwju73ghw53f74yqjhrevtyxs43h2yg
  - path_regex: .*staging/.*.yaml
    encrypted_regex: ^(data|stringData)$
    age: age1fapwknfa6lm0rmpxe4dkuyjpcz9wwju73ghw53f74yqjhrevtyxs43h2yg
  # Production secrets
  - path_regex: .*prod/.*values-secret.yaml
    age: age1us3r24et6a5kn8e4plqtvghchpuyj56n7errv72stqhgxq2l8dhsrem3u7
  - path_regex: .*prod/.*.yaml
    encrypted_regex: ^(data|stringData)$
    age: age1us3r24et6a5kn8e4plqtvghchpuyj56n7errv72stqhgxq2l8dhsrem3u7
